package com.stack_overflow_data_analysis.models

case class RawResponseRow(
       id:Int,
       collector: String,
       country: String,
       subRegion: String,
       region: String,
       ageRange: String,
       ageMidPoint: Double,
       gender: String,
       selfIdentification: String,
       occupation: String,
       occupationGroup: String,
       experienceRange: String,
       experienceMidpoint: String,
       salaryRange: String,
       salaryMidpoint: String,
       bigMacIndex: String,
       techDo: String,
       techWant: String,
       aliens: String,
       programmingAbility: String,
       employmentStatus: String,
       industry: String,
       companySizeRange: String,
       teamSizeRange: String,
       womenOnTeam: Int,
       remote: String,
       jobSatisfaction: String,
       jobDiscovery: String,
       devEnvironment: String,
       commitFrequency: String,
       hobby: String,
       dogsVsCats: String,
       desktopOs: String,
       unitTesting: String,
       stackOverflowRepRange: String,
       stackOverflowVisitFrequency: String,
       whyLearnNewTech: String,
       education: String,
       openToNewJob: String,
       newJobValue: String,
       jobSearchAnnoyance: String,
       googleInterviewLikelihood: String,
       howToImproveInterviewProcess: String
    )

